on: [push]

jobs:
  local_development:
    runs-on: ubuntu-latest
    name: Testing action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download
        run: |
         wget https://github.com/yt-dlp/yt-dlp/releases/download/2023.06.22/yt-dlp
         chmod +x yt-dlp
         ./yt-dlp -f source https://drive.google.com/file/d/17NLFdNN3gGimuy-ypJgW9yiEpbxjBAKI
         
      - name: upload
        uses: ./ # Uses an action in the root directory
        with:
          DROPBOX_ACCESS_TOKEN: sl.BhrXaavMlW3sR2bsWHyJH3IGR_QjJJzoV4JZQe7zcdxKHV1cE_GeXXTnadsU_QB0DjMO4zddWCGXWhwdNwHBG2WwAmYhr2OGLr_yv2Dy_u2nhHKdEbmW4AjbL4DwYeVvjwxjJ-SdU9Vy
          DROPBOX_DESTINATION_PATH_PREFIX: "/"
          GLOB: "AtomX_Packs_Collection_2023.part10.rar"
          DEBUG: false
